// Bangladesh Administrative Data
// 8 Divisions, 64 Districts, ~495 Upazilas (Thanas)
// Source: Bangladesh government data / Wikipedia / github.com/ifahimreza/bangladesh-geojson

const List<String> bangladeshDistricts = [
  // Barishal Division
  'Barguna',
  'Barishal',
  'Bhola',
  'Jhalokati',
  'Patuakhali',
  'Pirojpur',
  // Chattogram Division
  'Bandarban',
  'Brahmanbaria',
  'Chandpur',
  'Chattogram',
  'Cumilla',
  "Cox's Bazar",
  'Feni',
  'Khagrachhari',
  'Lakshmipur',
  'Noakhali',
  'Rangamati',
  // Dhaka Division
  'Dhaka',
  'Faridpur',
  'Gazipur',
  'Gopalganj',
  'Kishoreganj',
  'Madaripur',
  'Manikganj',
  'Munshiganj',
  'Narayanganj',
  'Narsingdi',
  'Rajbari',
  'Shariatpur',
  'Tangail',
  // Khulna Division
  'Bagerhat',
  'Chuadanga',
  'Jashore',
  'Jhenaidah',
  'Khulna',
  'Kushtia',
  'Magura',
  'Meherpur',
  'Narail',
  'Satkhira',
  // Mymensingh Division
  'Jamalpur',
  'Mymensingh',
  'Netrokona',
  'Sherpur',
  // Rajshahi Division
  'Bogura',
  'Joypurhat',
  'Naogaon',
  'Natore',
  'Nawabganj',
  'Pabna',
  'Rajshahi',
  'Sirajganj',
  // Rangpur Division
  'Dinajpur',
  'Gaibandha',
  'Kurigram',
  'Lalmonirhat',
  'Nilphamari',
  'Panchagarh',
  'Rangpur',
  'Thakurgaon',
  // Sylhet Division
  'Habiganj',
  'Moulvibazar',
  'Sunamganj',
  'Sylhet',
];

const Map<String, List<String>> thanasByDistrict = {
  // ── Barishal Division ──────────────────────────────────────
  'Barguna': [
    'Amtali',
    'Bamna',
    'Barguna Sadar',
    'Betagi',
    'Patharghata',
    'Taltali',
  ],
  'Barishal': [
    'Agailjhara',
    'Babuganj',
    'Bakerganj',
    'Banaripara',
    'Barisal Sadar',
    'Gaurnadi',
    'Hizla',
    'Mehendiganj',
    'Muladi',
    'Wazirpur',
  ],
  'Bhola': [
    'Bhola Sadar',
    'Burhanuddin',
    'Char Fasson',
    'Daulatkhan',
    'Lalmohan',
    'Manpura',
    'Tazumuddin',
  ],
  'Jhalokati': [
    'Jhalokati Sadar',
    'Kathalia',
    'Nalchity',
    'Rajapur',
  ],
  'Patuakhali': [
    'Bauphal',
    'Dashmina',
    'Dumki',
    'Galachipa',
    'Kalapara',
    'Mirzaganj',
    'Patuakhali Sadar',
    'Rangabali',
  ],
  'Pirojpur': [
    'Bhandaria',
    'Kaukhali',
    'Mathbaria',
    'Nazirpur',
    'Nesarabad',
    'Pirojpur Sadar',
    'Zianagar',
  ],

  // ── Chattogram Division ────────────────────────────────────
  'Bandarban': [
    'Ali Kadam',
    'Bandarban Sadar',
    'Lama',
    'Naikhongchhari',
    'Rowangchhari',
    'Ruma',
    'Thanchi',
  ],
  'Brahmanbaria': [
    'Akhaura',
    'Ashuganj',
    'Bancharampur',
    'Bijoynagar',
    'Brahmanbaria Sadar',
    'Kasba',
    'Nabinagar',
    'Nasirnagar',
    'Sarail',
  ],
  'Chandpur': [
    'Chandpur Sadar',
    'Faridganj',
    'Haimchar',
    'Haziganj',
    'Kachua',
    'Matlab Dakkhin',
    'Matlab Uttar',
    'Shahrasti',
  ],
  'Chattogram': [
    'Anwara',
    'Banshkhali',
    'Boalkhali',
    'Chandanaish',
    'Chattogram Sadar',
    'Fatikchhari',
    'Hathazari',
    'Lohagara',
    'Mirsharai',
    'Patiya',
    'Rangunia',
    'Raozan',
    'Sandwip',
    'Satkania',
    'Sitakunda',
  ],
  'Cumilla': [
    'Barura',
    'Brahmanpara',
    'Burichong',
    'Chandina',
    'Chauddagram',
    'Comilla Sadar',
    'Comilla Sadar South',
    'Daudkandi',
    'Debidwar',
    'Homna',
    'Laksam',
    'Meghna',
    'Monohorgonj',
    'Muradnagar',
    'Nangalkot',
    'Titas',
  ],
  "Cox's Bazar": [
    'Chakaria',
    "Cox's Bazar Sadar",
    'Kutubdia',
    'Maheshkhali',
    'Pekua',
    'Ramu',
    'Teknaf',
    'Ukhia',
  ],
  'Feni': [
    'Chagalnaiya',
    'Daganbhuiyan',
    'Feni Sadar',
    'Fhulgazi',
    'Parshuram',
    'Sonagazi',
  ],
  'Khagrachhari': [
    'Dighinala',
    'Khagrachhari Sadar',
    'Lakshmichhari',
    'Mahalchhari',
    'Manikchhari',
    'Matiranga',
    'Panchhari',
    'Ramgarh',
  ],
  'Lakshmipur': [
    'Kamalnagar',
    'Lakshmipur Sadar',
    'Raipur',
    'Ramganj',
    'Ramgati',
  ],
  'Noakhali': [
    'Begumganj',
    'Chatkhil',
    'Companyganj',
    'Hatia',
    'Kabirkhat',
    'Noakhali Sadar',
    'Senbagh',
    'Sonaimuri',
    'Subarnachar',
  ],
  'Rangamati': [
    'Bagaichhari',
    'Barkal',
    'Belaichhari',
    'Juraichhari',
    'Kaptai',
    'Kaukhali',
    'Langadu',
    'Nannerchar',
    'Rajasthali',
    'Rangamati Sadar',
  ],

  // ── Dhaka Division ─────────────────────────────────────────
  'Dhaka': [
    'Dhamrai',
    'Dohar',
    'Keraniganj',
    'Nawabganj',
    'Savar',
  ],
  'Faridpur': [
    'Alfadanga',
    'Bhanga',
    'Boalmari',
    'Charbhadrasan',
    'Faridpur Sadar',
    'Madhukhali',
    'Nagarkanda',
    'Sadarpur',
    'Saltha',
  ],
  'Gazipur': [
    'Gazipur Sadar',
    'Kaliakoir',
    'Kaliganj',
    'Kapasia',
    'Sreepur',
    'Tongi',
  ],
  'Gopalganj': [
    'Gopalganj Sadar',
    'Kashiani',
    'Kotalipara',
    'Muksudpur',
    'Tungipara',
  ],
  'Kishoreganj': [
    'Austagram',
    'Bajitpur',
    'Bhairab',
    'Hossainpur',
    'Itna',
    'Karimganj',
    'Katiadi',
    'Kishoreganj Sadar',
    'Kuliarchar',
    'Mithamain',
    'Nikli',
    'Pakundia',
    'Tarail',
  ],
  'Madaripur': [
    'Kalkini',
    'Madaripur Sadar',
    'Rajoir',
    'Shibchar',
  ],
  'Manikganj': [
    'Daulatpur',
    'Ghior',
    'Harirampur',
    'Manikganj Sadar',
    'Saturia',
    'Shibalaya',
    'Singair',
  ],
  'Munshiganj': [
    'Gazaria',
    'Lohajang',
    'Munshiganj Sadar',
    'Sirajdikhan',
    'Sreenagar',
    'Tongibari',
  ],
  'Narayanganj': [
    'Araihazar',
    'Bandor',
    'Narayanganj Sadar',
    'Rupganj',
    'Sonargaon',
  ],
  'Narsingdi': [
    'Belabo',
    'Monohardi',
    'Narsingdi Sadar',
    'Palash',
    'Raipura',
    'Shibpur',
  ],
  'Rajbari': [
    'Baliakandi',
    'Goalandaghat',
    'Kalukhali',
    'Pangsha',
    'Rajbari Sadar',
  ],
  'Shariatpur': [
    'Bhedarganj',
    'Damudya',
    'Gosairhat',
    'Naria',
    'Shariatpur Sadar',
    'Zanjira',
  ],
  'Tangail': [
    'Basail',
    'Bhuapur',
    'Delduar',
    'Dhanbari',
    'Ghatail',
    'Gopalpur',
    'Kalihati',
    'Madhupur',
    'Mirzapur',
    'Nagarpur',
    'Sakhipur',
    'Tangail Sadar',
  ],

  // ── Khulna Division ────────────────────────────────────────
  'Bagerhat': [
    'Bagerhat Sadar',
    'Chitalmari',
    'Fakirhat',
    'Kachua',
    'Mollahat',
    'Mongla',
    'Morrelganj',
    'Rampal',
    'Sarankhola',
  ],
  'Chuadanga': [
    'Alamdanga',
    'Chuadanga Sadar',
    'Damurhuda',
    'Jibannagar',
  ],
  'Jashore': [
    'Abhaynagar',
    'Bagherpara',
    'Chaugachha',
    'Jhikargachha',
    'Keshabpur',
    'Jashore Sadar',
    'Manirampur',
    'Sharsha',
  ],
  'Jhenaidah': [
    'Harinakunda',
    'Jhenaidah Sadar',
    'Kaliganj',
    'Kotchandpur',
    'Maheshpur',
    'Shailkupa',
  ],
  'Khulna': [
    'Batiaghata',
    'Dacope',
    'Daulatpur',
    'Dighalia',
    'Dumuria',
    'Koyra',
    'Paikgachha',
    'Phultala',
    'Rupsha',
    'Terokhada',
  ],
  'Kushtia': [
    'Bheramara',
    'Daulatpur',
    'Khoksa',
    'Kumarkhali',
    'Kushtia Sadar',
    'Mirpur',
  ],
  'Magura': [
    'Magura Sadar',
    'Mohammadpur',
    'Shalikha',
    'Sreepur',
  ],
  'Meherpur': [
    'Gangni',
    'Meherpur Sadar',
    'Mujibnagar',
  ],
  'Narail': [
    'Kalia',
    'Lohagara',
    'Narail Sadar',
  ],
  'Satkhira': [
    'Assasuni',
    'Debhata',
    'Kalaroa',
    'Kaliganj',
    'Satkhira Sadar',
    'Shyamnagar',
    'Tala',
  ],

  // ── Mymensingh Division ────────────────────────────────────
  'Jamalpur': [
    'Baksiganj',
    'Dewanganj',
    'Islampur',
    'Jamalpur Sadar',
    'Madarganj',
    'Melandaha',
    'Sarishabari',
  ],
  'Mymensingh': [
    'Bhaluka',
    'Dhobaura',
    'Fulbaria',
    'Gaffargaon',
    'Gauripur',
    'Haluaghat',
    'Ishwarganj',
    'Muktagachha',
    'Mymensingh Sadar',
    'Nandail',
    'Phulpur',
    'Trishal',
  ],
  'Netrokona': [
    'Atpara',
    'Barhatta',
    'Durgapur',
    'Kalmakanda',
    'Kendua',
    'Khaliajuri',
    'Madan',
    'Mohanganj',
    'Netrokona Sadar',
    'Purbadhala',
  ],
  'Sherpur': [
    'Jhenaigati',
    'Nakla',
    'Nalitabari',
    'Sherpur Sadar',
    'Sreebardi',
  ],

  // ── Rajshahi Division ──────────────────────────────────────
  'Bogura': [
    'Adamdighi',
    'Bogura Sadar',
    'Dhunat',
    'Dhupchanchia',
    'Gabtali',
    'Kahaloo',
    'Nandigram',
    'Sariakandi',
    'Shajahanpur',
    'Sherpur',
    'Shibganj',
    'Sonatala',
  ],
  'Joypurhat': [
    'Akkelpur',
    'Joypurhat Sadar',
    'Kalai',
    'Khetlal',
    'Panchbibi',
  ],
  'Naogaon': [
    'Atrai',
    'Badalgachhi',
    'Dhamoirhat',
    'Manda',
    'Mahadebpur',
    'Naogaon Sadar',
    'Niamatpur',
    'Patnitala',
    'Porsha',
    'Raninagar',
    'Sapahar',
  ],
  'Natore': [
    'Bagatipara',
    'Baraigram',
    'Gurudaspur',
    'Lalpur',
    'Natore Sadar',
    'Singra',
  ],
  'Nawabganj': [
    'Bholahat',
    'Gomastapur',
    'Nachole',
    'Nawabganj Sadar',
    'Rohanpur',
    'Shibganj',
  ],
  'Pabna': [
    'Atgharia',
    'Bera',
    'Bhangura',
    'Chatmohar',
    'Faridpur',
    'Ishwardi',
    'Pabna Sadar',
    'Santhia',
    'Sujanagar',
  ],
  'Rajshahi': [
    'Bagha',
    'Bagmara',
    'Charghat',
    'Durgapur',
    'Godagari',
    'Mohanpur',
    'Paba',
    'Puthia',
    'Tanore',
  ],
  'Sirajganj': [
    'Belkuchi',
    'Chauhali',
    'Kamarkhanda',
    'Kazipur',
    'Raiganj',
    'Shahjadpur',
    'Sirajganj Sadar',
    'Tarash',
    'Ullapara',
  ],

  // ── Rangpur Division ───────────────────────────────────────
  'Dinajpur': [
    'Birampur',
    'Birganj',
    'Biral',
    'Bochaganj',
    'Chirirbandar',
    'Dinajpur Sadar',
    'Fulbari',
    'Ghoraghat',
    'Hakimpur',
    'Kaharole',
    'Khansama',
    'Nawabganj',
    'Parbatipur',
  ],
  'Gaibandha': [
    'Fulchhari',
    'Gaibandha Sadar',
    'Gobindaganj',
    'Palashbari',
    'Sadullapur',
    'Saghata',
    'Sundarganj',
  ],
  'Kurigram': [
    'Bhurungamari',
    'Char Rajibpur',
    'Chilmari',
    'Kurigram Sadar',
    'Nageshwari',
    'Phulbari',
    'Rajarhat',
    'Raumari',
    'Ulipur',
  ],
  'Lalmonirhat': [
    'Aditmari',
    'Hatibandha',
    'Kaliganj',
    'Lalmonirhat Sadar',
    'Patgram',
  ],
  'Nilphamari': [
    'Dimla',
    'Domar',
    'Jaldhaka',
    'Kishoreganj',
    'Nilphamari Sadar',
    'Saidpur',
  ],
  'Panchagarh': [
    'Atwari',
    'Boda',
    'Debiganj',
    'Panchagarh Sadar',
    'Tetulia',
  ],
  'Rangpur': [
    'Badarganj',
    'Gangachara',
    'Kaunia',
    'Mithapukur',
    'Pirgachha',
    'Pirganj',
    'Rangpur Sadar',
    'Taraganj',
  ],
  'Thakurgaon': [
    'Baliadangi',
    'Haripur',
    'Pirganj',
    'Ranisankail',
    'Thakurgaon Sadar',
  ],

  // ── Sylhet Division ────────────────────────────────────────
  'Habiganj': [
    'Ajmiriganj',
    'Bahubal',
    'Baniachong',
    'Chunarughat',
    'Habiganj Sadar',
    'Lakhai',
    'Madhabpur',
    'Nabiganj',
  ],
  'Moulvibazar': [
    'Barlekha',
    'Juri',
    'Kamalganj',
    'Kulaura',
    'Moulvibazar Sadar',
    'Rajnagar',
    'Sreemangal',
  ],
  'Sunamganj': [
    'Bishwamvarpur',
    'Chhatak',
    'Derai',
    'Dharampasha',
    'Dowarabazar',
    'Jagannathpur',
    'Jamalganj',
    'Sullah',
    'Sunamganj Sadar',
    'Tahirpur',
  ],
  'Sylhet': [
    'Balaganj',
    'Beanibazar',
    'Bishwanath',
    'Companiganj',
    'Fenchuganj',
    'Golapganj',
    'Gowainghat',
    'Jaintiapur',
    'Kanaighat',
    'Osmani Nagar',
    'Sylhet Sadar',
    'South Surma',
    'Zakiganj',
  ],
};
